# LifeDJIK: copyright will be added later

# LifeDJIK: CPU
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a8
TARGET_ARCH_VARIANT_FPU := neon

ARCH_ARM_HAVE_THUMB_SUPPORT := true
ARCH_ARM_HAVE_FAST_INTERWORKING := true
ARCH_ARM_HAVE_64BIT_DATA := true
ARCH_ARM_HAVE_HALFWORD_MULTIPLY := true
ARCH_ARM_HAVE_CLZ := true
ARCH_ARM_HAVE_FFS := true
ARCH_ARM_HAVE_ARMV7A := true
ARCH_ARM_HAVE_VFP := true
ARCH_ARM_HAVE_VFP_D32 := true
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_TLS_REGISTER := true
# LifeDJIK: ---

# LifeDJIK: disable unneeded parts
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
# LifeDJIK: ---

# LifeDJIK: platform settings
TARGET_BOARD_PLATFORM := rk29
TARGET_BOARD_HARDWARE := rk29board
TARGET_BOARD_PLATFORM_GPU := Vivante-GC800
TARGET_BOARD_INFO_FILE := device/enot/j117/device/data/board-info.txt

TARGET_BOOTLOADER_BOARD_NAME := $(TARGET_BOARD_HARDWARE)
# LifeDJIK: ---

# LifeDJIK: kernel
TARGET_KERNEL_SOURCE := device/enot/j117/kernel
TARGET_KERNEL_CONFIG := j117_defconfig

BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_BASE :=
BOARD_KERNEL_PAGESIZE :=
# LifeDJIK: ---

# LifeDJIK: partitions
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

BOARD_PARAMETERIMAGE_PARTITION_SIZE := 4194304
BOARD_BOOTIMAGE_PARTITION_SIZE := 4194304
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 8388608
BOARD_KERNELIMAGE_PARTITION_SIZE := 8388608
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 536870912
# ^-> this is not true now (much bigger), but who cares?
BOARD_FLASH_BLOCK_SIZE := 16384
# LifeDJIK: ---

# LifeDJIK: release tools
BOARD_CUSTOM_BOOTIMG_MK := device/enot/j117/device/tools/tools.mk
# LifeDJIK: ---

# LifeDJIK: recovery
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_CUSTOM_RECOVERY_KEYMAPPING:= ../../device/enot/j117/recovery/recovery_keys.c
# LifeDJIK: ---

# LifeDJIK: camera
USE_CAMERA_STUB := false
BOARD_NEEDS_MEMORYHEAPPMEM := true
# LifeDJIK: ---

# LifeDJIK: GPU
BOARD_EGL_CFG := device/enot/j117/device/data/egl.cfg
COMMON_GLOBAL_CFLAGS += -DMISSING_EGL_EXTERNAL_IMAGE -DMISSING_EGL_PIXEL_FORMAT_YV12 -DMISSING_GRALLOC_BUFFERS
#~ USE_OPENGL_RENDERER := false
USE_OPENGL_RENDERER := true
#~ BOARD_USES_HWCOMPOSER := true
#~ TARGET_DISABLE_TRIPLE_BUFFERING := true
#~ BOARD_EGL_NEEDS_LEGACY_FB := true
# LifeDJIK: ---

# LifeDJIK: ION
TARGET_USES_ION := true
TARGET_DISABLE_SYSTEM_CORE_LIBION := true
# LifeDJIK: ---

# LifeDJIK: OMX
BOARD_USES_PROPRIETARY_OMX := ROCKCHIP
# LifeDJIK: ---

# LifeDJIK: WiFi
BOARD_WIFI_VENDOR := realtek
BOARD_WLAN_DEVICE := rtl8192cu

CONFIG_AP := y
CONFIG_P2P := y
CONFIG_DRIVER_NL80211 := y
TARGET_CUSTOM_WIFI := ../../device/enot/j117/hardware/realtek/wlan/libhardware_legacy/wifi/wifi_realtek.c

WPA_SUPPLICANT_VERSION := VER_0_8_X_REALTEK

BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_rtl

BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_rtl

WIFI_DRIVER_MODULE_NAME := wlan
WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/wlan.ko"
WIFI_DRIVER_MODULE_ARG := ""

WIFI_FIRMWARE_LOADER := ""

WIFI_DRIVER_FW_PATH_STA := ""
WIFI_DRIVER_FW_PATH_AP := ""
WIFI_DRIVER_FW_PATH_P2P := ""
WIFI_DRIVER_FW_PATH_PARAM := ""
# LifeDJIK: ---

# LifeDJIK: browser
ENABLE_WEBGL := true
TARGET_FORCE_CPU_UPLOAD := true
# LifeDJIK: ---

# LifeDJIK: porting
# BOARD_USES_OVERLAY -- found only in device/ti/panda/BoardConfig.mk
# BOARD_USES_COPYBIT -- not found
# TARGET_DO_NOT_SETS_CAN_DRAW -- not found
# TARGET_LIBAGL_USE_GRALLOC_COPYBITS -- not found
# BOARD_USES_HGL -- found only in device/ti/panda/BoardConfig.mk
# BOARD_AVOID_DRAW_TEXTURE_EXTENSION -- not found
# BOARD_HAS_LARGE_FILESYSTEM -- found only in build/tools/device/BoardConfig.mk.template
# BOARD_USES_HWCOMPOSER -- not found
# BOARD_EGL_NEEDS_LEGACY_FB -- not found
# BOARD_NO_RGBX_8888 -- not found
# BOARD_USE_SCREENCAP -- not found
# BOARD_NEEDS_MEMORYHEAPPMEM -- not found
# BUILD_PV_VIDEO_ENCODERS -- not found
# BUILD_PV_2WAY -- not found
# BUILD_PV_TEST_APPS -- not found
# USE_CAMERA_STUB -- found only in BoardConfig.mk and setup-makefiles.sh
# BOARD_USE_FROYO_LIBCAMERA -- not found
# BOARD_CAMERA_USE_GETBUFFERINFO -- not found
# BOARD_CAMERA_LIBRARIES -- not found
# USE_OVERLAY_FORMAT_YCbCr_420_SP -- not found
# BOARD_V4L2_DEVICE -- not found
# BOARD_CAMERA_DEVICE -- not found
# BUILD_WITH_FULL_STAGEFRIGHT -- not found
# BOARD_USE_USB_MASS_STORAGE_SWITCH -- not found
# TARGET_HAVE_HDMI_OUT -- not found
# BOARD_USES_HDMI -- found only in samsung
#~ COMMON_GLOBAL_CFLAGS += -DNEVER_DEFAULT_TO_ASYNC_MODE -DSURFACEFLINGER_FORCE_SCREEN_RELEASE
#~ COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=15 -DNO_RGBX_8888 -DMISSING_GRALLOC_BUFFERS
#~ COMMON_GLOBAL_CFLAGS += -DNO_RGBX_8888 -DMISSING_GRALLOC_BUFFERS
#~ COMMON_GLOBAL_CFLAGS += -DNO_RGBX_8888 -DMISSING_EGL_PIXEL_FORMAT_YV12
#~ NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
#~ COMMON_GLOBAL_CFLAGS += -DNO_RGBX_8888
# ^-- not sure if this is needed
#~ BOARD_USES_ALSA_AUDIO := true
#~ BOARD_USES_AUDIO_LEGACY := true
# TARGET_USES_OLD_LIBSENSORS_HAL := true
# TARGET_SENSORS_NO_OPEN_CHECK := true
# BOARD_MOBILEDATA_INTERFACE_NAME := "pdp0"
# WITH_DEXPREOPT := true
# WITH_JIT := true
# WITH_JIT_TUNING := true
# ENABLE_JSC_JIT := true
# JS_ENGINE := v8
# TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/s3c-usbgadget/gadget/lun"
# BOARD_UMS_LUNFILE := "/sys/devices/platform/s3c-usbgadget/gadget/lun0/file"
#~ BOARD_CAMERA_USE_MM_HEAP := true
# LifeDJIK: ---
