#
# Makefile for the Linux Wireless network device drivers.
#
obj-$(CONFIG_BCM4329)   += bcm4329/
obj-$(CONFIG_MV8686)   += mv8686/
obj-$(CONFIG_BCM4319)   += bcm4319/
obj-$(CONFIG_RTL8192CU)   += rtl8192cu/
obj-$(CONFIG_AR6003)   += ar6003/
obj-y += wifi_sys/
obj-m += wifi_launcher/
