LOCAL_PATH := $(call my-dir)

#~ include $(CLEAR_VARS)
#~ LOCAL_COPY_HEADERS_TO :=
#~ LOCAL_COPY_HEADERS := include/gralloc_priv.h
#~ include $(BUILD_COPY_HEADERS)
#~ 
#~ include $(CLEAR_VARS)
#~ LOCAL_SRC_FILES := prebuilt/gralloc.rk29board.so
#~ LOCAL_MODULE := $(basename $(notdir $(LOCAL_SRC_FILES)))
#~ LOCAL_MODULE_TAGS := optional
#~ LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#~ LOCAL_MODULE_SUFFIX := $(suffix $(LOCAL_SRC_FILES))
#~ OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
#~ LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
#~ include $(BUILD_PREBUILT)
#~ 
#~ include $(CLEAR_VARS)
#~ LOCAL_SRC_FILES := prebuilt/copybit.rk29board.so
#~ LOCAL_MODULE := $(basename $(notdir $(LOCAL_SRC_FILES)))
#~ LOCAL_MODULE_TAGS := optional
#~ LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#~ LOCAL_MODULE_SUFFIX := $(suffix $(LOCAL_SRC_FILES))
#~ OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
#~ LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
#~ include $(BUILD_PREBUILT)
#~ 
#~ ifeq ($(BOARD_USES_HWCOMPOSER), true)
#~ include $(CLEAR_VARS)
#~ LOCAL_SRC_FILES := prebuilt/hwcomposer.rk29board.so
#~ LOCAL_MODULE := $(basename $(notdir $(LOCAL_SRC_FILES)))
#~ LOCAL_MODULE_TAGS := optional
#~ LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#~ LOCAL_MODULE_SUFFIX := $(suffix $(LOCAL_SRC_FILES))
#~ OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
#~ LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw
#~ include $(BUILD_PREBUILT)
#~ endif
#~ 
#~ include $(CLEAR_VARS)
#~ LOCAL_SRC_FILES := prebuilt/libEGL_VIVANTE.so
#~ LOCAL_MODULE := $(basename $(notdir $(LOCAL_SRC_FILES)))
#~ LOCAL_MODULE_TAGS := optional
#~ LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#~ LOCAL_MODULE_SUFFIX := $(suffix $(LOCAL_SRC_FILES))
#~ OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
#~ LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
#~ include $(BUILD_PREBUILT)
#~ 
#~ include $(CLEAR_VARS)
#~ LOCAL_SRC_FILES := prebuilt/libGLESv1_CM_VIVANTE.so
#~ LOCAL_MODULE := $(basename $(notdir $(LOCAL_SRC_FILES)))
#~ LOCAL_MODULE_TAGS := optional
#~ LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#~ LOCAL_MODULE_SUFFIX := $(suffix $(LOCAL_SRC_FILES))
#~ OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
#~ LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
#~ include $(BUILD_PREBUILT)
#~ 
#~ include $(CLEAR_VARS)
#~ LOCAL_SRC_FILES := prebuilt/libGLESv2_VIVANTE.so
#~ LOCAL_MODULE := $(basename $(notdir $(LOCAL_SRC_FILES)))
#~ LOCAL_MODULE_TAGS := optional
#~ LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#~ LOCAL_MODULE_SUFFIX := $(suffix $(LOCAL_SRC_FILES))
#~ OVERRIDE_BUILT_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
#~ LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
#~ include $(BUILD_PREBUILT)
#~ 
#~ include $(CLEAR_VARS)
#~ LOCAL_MODULE_TAGS := optional
#~ LOCAL_PREBUILT_LIBS := \
#~     prebuilt/libGAL.so \
#~     prebuilt/libGLSLC.so
#~ include $(BUILD_MULTI_PREBUILT)
