LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := upgrade_tool
LOCAL_MODULE := $(basename $(notdir $(LOCAL_SRC_FILES)))
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_SUFFIX := $(suffix $(LOCAL_SRC_FILES))
LOCAL_MODULE_PATH := $(HOST_OUT_EXECUTABLES)
include $(BUILD_PREBUILT)
