LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := rkcrc
LOCAL_MODULE_PATH := $(HOST_OUT_EXECUTABLES)
LOCAL_SRC_FILES := rkcrc.c
LOCAL_MODULE_TAGS := optional
include $(BUILD_HOST_EXECUTABLE)
